steps:
    - "fastqc"
    - "trim"
    - "bwa"
    - "multiqc"
    - "sort"
    - "dedup"
    - "split"
    - "postalignment"
    - "haplotype"
    - "merge"
    - "combine_vcf"
    - "filter"
fastqc: []
trim:
    - 4     #number of threads
    - 36    #minlen for trimmomatic
bwa:
    - 4     #number of threads
    - "ILLUMINA"    #platform technology
multiqc: []
sort:
    - 4     #number of threads
dedup:
    - 4     #number of threads
split:
    - 1     #number of threads
postalignment:
    - 2     #number of threads
haplotype:
    - 4     #number of threads
merge:
    - 4     #number of threads
    - "True"    #if vcf files should be merged or not
combine_vcf: 
    - 4     #number of threads
filter:
    - 4     #number of threads
