steps:
   - "fastqc"
   - "trim"
   - "cut_adapt"
   - "bowtie2_count"
   - "merge_counts"
   - "multiqc"
fastqc: []
trim:
   - 1  # number of threads
   - 15  # drop the read if it is below this minimum length
cut_adapt:
   - 1  # number of threads
   - 2  # drop the read if it is below this minimum length: to avoid warnings
bowtie2_count: []  # alignment + counting for individual samfiles
merge_counts: []
multiqc: []

