steps:
   - "fastqc"
   - "trim"
   - "cut_adapt"
   - "bowtie2"
   - "counting"
   - "multiqc"
fastqc: []
trim:
   - 1  # number of threads
   - 15  # drop the read if it is below this minimum length
cut_adapt:
   - 1  # number of threads
   - 2  # drop the read if it is below this minimum length: to avoid warnings
bowtie2: []
counting: []
multiqc: []

