steps:
   - "star_rsem_fastqc"
   - "star_rsem_trim"
   - "star_rsem_calculate_expression"
   - "star_rsem_summary"
   - "star_rsem_multiqc"
star_rsem_fastqc: []
star_rsem_trim:
   - 5      # number of threads
   - 27     # min length to keep
star_rsem_calculate_expression:
   - 5
star_rsem_summary: []
star_rsem_multiqc: []
