steps:
   - "star_gatk_make_group"
   - "star_gatk_fastqc"
   - "star_gatk_trim"
   - "star_gatk_align"
   - "star_gatk_variant_calling"  # only in star_gatk
   - "star_gatk_multiqc"
star_gatk_make_group: []
star_gatk_fastqc: []
star_gatk_trim:
   - 5      # number of threads
   - 27     # min length to keep
star_gatk_align:
   - 4
star_gatk_variant_calling:
   - 4
star_gatk_multiqc: []
