steps:
   - "kallisto_fastqc"
   - "kallisto_trim"
   - "kallisto_align" # from here, kallisto-specific
   - "kallisto_count"
   - "kallisto_merge"
   - "kallisto_differential_calculate" # only for kallisto
kallisto_fastqc: []
kallisto_trim:
   - 5      # number of threads
   - 27     # 36 for paired end, handled in shell script
kallisto_align:
   - 4      # number of threads
kallisto_count: []
kallisto_merge:
   - 1      # number of threads
   - "kallisto_deseq_workflow"


# different for paired/single end
