steps:
   - "star_htseq_make_group"
   - "star_htseq_fastqc"
   - "star_htseq_trim"
   - "star_htseq_align"
   - "star_htseq_count"
   - "star_htseq_merge"
   - "star_htseq_multiqc"
star_htseq_make_group: []
star_htseq_fastqc: []
star_htseq_trim:
   - 5      # number of threads
   - 27     # min length to keep
star_htseq_align:
   - 4      # number of threads
star_htseq_count: []
star_htseq_merge: []
star_htseq_multiqc: []
