## Configuration file for tool methods
fastqc:
    script_name: "fastqc"
    download_suffix: ~
    input_is_output: False
    can_be_zipped: True
    uses_chromosomes: False
trim:
    script_name: "trim"
    download_suffix: ~
    input_is_output: False
    can_be_zipped: True
    uses_chromosomes: False
bwa:
    script_name: "DNASeq/bwa"
    download_suffix: ".trim{}"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
sort:
    script_name: "DNASeq/sort"
    download_suffix: ".bam"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
dedup:
    script_name: "DNASeq/dedup"
    download_suffix: ".sort.bam"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
split:
    script_name: "DNASeq/split"
    download_suffix: ".dedup.bam"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: True 
postalignment:
    script_name: "DNASeq/post"
    download_suffix: ".{}.bam"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: True 
haplotype:
    script_name: "DNASeq/haplo"
    download_suffix: ".final.{}.bam"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: True 
mutect:
    script_name: "DNASeq/mutect"
    download_suffix: ".final.{}.bam"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: True
    by_pair: True
merge:
    script_name: "DNASeq/merge"
    download_suffix: ".g.vcf"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
bam_merge:
    script_name: "DNASeq/merge"
    download_suffix: ".g.vcf"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
pair_vcf_merge:
    script_name: "DNASeq/pair_merge"
    download_suffix: ".vcf"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    by_pair: True
combine_vcf:
    script_name: "DNASeq/group_vcf"
    download_suffix: ".merged.vcf"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    by_group: True
filter:
    script_name: "DNASeq/filter"
    download_suffix: ".g.vcf.gz"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    by_group: True

# SmallRNA specific #
cut_adapt:
    script_name: "SmallRNASeq/cutadapt"
    download_suffix: ~
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
bowtie2:  
    script_name: "SmallRNASeq/bowtie2"
    download_suffix: ".cut{}"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
counting:
    script_name: "SmallRNASeq/count"
    download_suffix: ".sam"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    all_samples: True

# ChiPSeq #
bowtie:
    script_name: "ChiPSeq/bowtie"
    download_suffix: ~
    input_is_output: False
    can_be_zipped: True
    uses_chromosomes: False
make_tag_directory:
    script_name: "ChiPSeq/make_tag_directory"
    download_suffix: ".sam"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
make_UCSC_file:
    script_name: "ChiPSeq/make_UCSC_file"
    download_suffix: ~
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
findpeaks:
    script_name: "ChiPSeq/findpeaks"
    download_suffix: ~
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    by_pair: True
annotate_peaks:
    script_name: "ChiPSeq/annotate_peaks"
    download_suffix: ~
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    by_pair: True
pos2bed:
    script_name: "ChiPSeq/pos2bed"
    download_suffix: ~
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    by_pair: True
find_motifs_genome:
    script_name: "ChiPSeq/find_motifs_genome"
    download_suffix: ~
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    by_pair: True


# MultiQC #
multiqc:
    script_name: "multiqc"
    download_suffix: ""
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    all_samples: True

# RNA-seq specific #
#
# Kallisto workflow:

kallisto_make_group:
    script_name: "RNASeq/make_group"
    download_suffix: ~
    input_is_output: False
    can_be_zipped: False
    uses_chromosomes: False
    all_samples: True
kallisto_fastqc:
    script_name: "fastqc"
    download_suffix: ~
    input_is_output: False
    can_be_zipped: True
    uses_chromosomes: False
kallisto_trim:
    script_name: "trim"
    download_suffix: ~
    input_is_output: False
    can_be_zipped: True
    uses_chromosomes: False
kallisto_align: 
    script_name: "RNASeq/k_align"
    download_suffix: ".trim{}"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
kallisto_count:
    script_name: "RNASeq/k_count"
    download_suffix: ~ 
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
kallisto_merge:
    script_name: "RNASeq/merge_counts"
    download_suffix: ~ 
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False

# Star_gatk workflow:
star_gatk_make_group:
    script_name: "RNASeq/make_group"
    download_suffix: ~
    input_is_output: False
    can_be_zipped: False
    uses_chromosomes: False
    all_samples: True
star_gatk_fastqc:
    script_name: "fastqc"
    download_suffix: ~
    input_is_output: False
    can_be_zipped: True
    uses_chromosomes: False
star_gatk_trim:
    script_name: "trim"
    download_suffix: ~
    input_is_output: False
    can_be_zipped: True
    uses_chromosomes: False
star_gatk_align:
    script_name: "RNASeq/gatk_align"
    download_suffix: ".trim{}"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
star_gatk_vc:
    script_name: "RNASeq/gatk_vc"
    download_suffix: ".Aligned.out.bam"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False

# Star_htseq workflow:
star_htseq_make_group:
    script_name: "RNASeq/make_group"
    download_suffix: ~
    input_is_output: False
    can_be_zipped: False
    uses_chromosomes: False
    all_samples: True
star_htseq_fastqc:
    script_name: "fastqc"
    download_suffix: ~
    input_is_output: False
    can_be_zipped: True
    uses_chromosomes: False
star_htseq_trim:
    script_name: "trim"
    download_suffix: ~
    input_is_output: False
    can_be_zipped: True
    uses_chromosomes: False
star_htseq_align:
    script_name: "RNASeq/ht_align"
    download_suffix: ".trim{}"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
star_htseq_count:
    script_name: "RNASeq/ht_count"
    download_suffix: ".Aligned.out.sorted.bam"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
star_htseq_merge:  # same with kallisto
    script_name: "RNASeq/merge_counts"
    download_suffix: "_counts.txt"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    all_samples: True
